import * as fs from "node:fs";
import * as path from "node:path";
import type {
  PlatformAdapter,
  NormalizedAppConfig,
  AndroidConfig,
  IconEntry,
  DeepLinkConfig,
} from "../types.js";
import { fileExists, readJsonFile } from "../utils.js";

/** Shape of twa-manifest.json as generated by Bubblewrap */
interface TwaManifest {
  packageId?: string;
  host?: string;
  name?: string;
  launcherName?: string;
  display?: string;
  themeColor?: string;
  startUrl?: string;
  signingKey?: { path?: string; alias?: string };
  appVersionName?: string;
  appVersionCode?: number;
  minSdkVersion?: number;
  fingerprints?: Array<{ type?: string; value?: string }>;
}

/** Shape of Digital Asset Links JSON */
interface AssetLinksEntry {
  relation?: string[];
  target?: {
    namespace?: string;
    package_name?: string;
    sha256_cert_fingerprints?: string[];
  };
}

/** Shape of a PWA manifest.json for icon extraction */
interface WebManifest {
  icons?: Array<{ src?: string; sizes?: string; type?: string }>;
}

const TWA_ICON_SIZES = ["192x192", "512x512", "1024x1024"];

export const twaAdapter: PlatformAdapter = {
  platform: "twa",

  detect(cwd: string): boolean {
    return fileExists(path.join(cwd, "twa-manifest.json"));
  },

  normalize(cwd: string): NormalizedAppConfig {
    const manifestPath = path.join(cwd, "twa-manifest.json");
    const manifest = readJsonFile<TwaManifest>(manifestPath);

    const packageId = manifest?.packageId ?? "unknown";
    const appName = manifest?.name ?? manifest?.launcherName ?? "Unknown App";
    const versionName = manifest?.appVersionName ?? "1";
    const versionCode = manifest?.appVersionCode ?? 1;
    const minSdkVersion = manifest?.minSdkVersion ?? 19;
    const signingConfigured =
      manifest?.signingKey != null && manifest.signingKey.path != null;

    // Fingerprints from twa-manifest.json
    const manifestFingerprints: string[] = (manifest?.fingerprints ?? [])
      .filter((fp) => fp.value != null)
      .map((fp) => fp.value as string);

    // Read Digital Asset Links for additional fingerprints
    const assetLinksPath = path.join(
      cwd,
      "public",
      ".well-known",
      "assetlinks.json",
    );
    const assetLinksFingerprints = readAssetLinksFingerprints(assetLinksPath);

    const android: AndroidConfig = {
      packageId,
      appName,
      versionCode,
      versionName,
      minSdkVersion,
      targetSdkVersion: 34,
      permissions: [],
      signingConfigured,
      assetLinksPath: fileExists(assetLinksPath) ? assetLinksPath : undefined,
      assetLinksFingerprints:
        assetLinksFingerprints.length > 0 ? assetLinksFingerprints : undefined,
      manifestFingerprints:
        manifestFingerprints.length > 0 ? manifestFingerprints : undefined,
    };

    // Icons: check public/icons/icon-{size}.png for standard sizes
    const icons = readIcons(cwd);

    // Deep links from host + startUrl
    const deepLinks: DeepLinkConfig[] = [];
    if (manifest?.host) {
      const routes: string[] = [];
      if (manifest.startUrl) {
        routes.push(manifest.startUrl);
      }
      deepLinks.push({ platform: "android", routes });
    }

    // Source code directories: filter to those that exist
    const candidateDirs = ["app/", "components/", "lib/", "src/"];
    const sourceCodeDirs = candidateDirs.filter((dir) => {
      const fullPath = path.join(cwd, dir);
      try {
        return fs.statSync(fullPath).isDirectory();
      } catch {
        return false;
      }
    });

    // Store listing path
    const storeListingPath = path.join(cwd, "docs", "appstore-listing.txt");

    return {
      platform: "twa",
      android,
      ios: undefined,
      appName,
      icons,
      privacyPolicyUrl: undefined,
      deepLinks,
      storeListingPath: fileExists(storeListingPath)
        ? storeListingPath
        : undefined,
      sourceCodeDirs: sourceCodeDirs.map((dir) => path.join(cwd, dir)),
      projectRoot: cwd,
    };
  },
};

function readAssetLinksFingerprints(assetLinksPath: string): string[] {
  const assetLinks = readJsonFile<AssetLinksEntry[]>(assetLinksPath);
  if (!Array.isArray(assetLinks)) return [];

  const fingerprints: string[] = [];
  for (const entry of assetLinks) {
    const certs = entry?.target?.sha256_cert_fingerprints;
    if (Array.isArray(certs)) {
      for (const cert of certs) {
        if (typeof cert === "string") {
          fingerprints.push(cert);
        }
      }
    }
  }
  return fingerprints;
}

function readIcons(cwd: string): IconEntry[] {
  const icons: IconEntry[] = [];

  // Check standard icon paths
  for (const size of TWA_ICON_SIZES) {
    const iconPath = path.join(cwd, "public", "icons", `icon-${size}.png`);
    icons.push({
      size,
      path: iconPath,
      exists: fileExists(iconPath),
    });
  }

  // Also try to read manifest.json for additional icon entries
  const webManifest = readJsonFile<WebManifest>(
    path.join(cwd, "public", "manifest.json"),
  );
  if (webManifest?.icons && Array.isArray(webManifest.icons)) {
    for (const icon of webManifest.icons) {
      if (!icon.sizes || !icon.src) continue;
      // Skip sizes we already checked
      if (TWA_ICON_SIZES.includes(icon.sizes)) continue;

      const iconPath = icon.src.startsWith("/")
        ? path.join(cwd, "public", icon.src)
        : path.join(cwd, "public", icon.src);
      icons.push({
        size: icon.sizes,
        path: iconPath,
        exists: fileExists(iconPath),
      });
    }
  }

  return icons;
}
